from runCsv import *
from ..data.consts import *


args = [
[ACUTE_PATH, ACUTE_HAS_HEADER, ACUTE_1_DATA_TYPES, ACUTE_IS_CLASSIFY, ACUTE_DELIM_WHITESPACE, ACUTE_1_OUTPUT],
[ACUTE_PATH, ACUTE_HAS_HEADER, ACUTE_2_DATA_TYPES, ACUTE_IS_CLASSIFY, ACUTE_DELIM_WHITESPACE, ACUTE_2_OUTPUT],
[BALANCE_PATH, BALANCE_HAS_HEADER, BALANCE_DATA_TYPES, BALANCE_IS_CLASSIFY, BALANCE_DELIM_WHITESPACE, BALANCE_OUTPUT],
[BANKNOTE_PATH, BANKNOTE_HAS_HEADER, BANKNOTE_DATA_TYPES, BANKNOTE_IS_CLASSIFY, BANKNOTE_DELIM_WHITESPACE, BANKNOTE_OUTPUT],
[BREAST_CANCER_DIAG_PATH, BREAST_CANCER_DIAG_HAS_HEADER, BREAST_CANCER_DIAG_DATA_TYPES, BREAST_CANCER_DIAG_IS_CLASSIFY, BREAST_CANCER_DIAG_DELIM_WHITESPACE, BREAST_CANCER_DIAG_OUTPUT],
[BREAST_CANCER_PROG_PATH, BREAST_CANCER_PROG_HAS_HEADER, BREAST_CANCER_PROG_CL_DATA_TYPES, BREAST_CANCER_PROG_CL_IS_CLASSIFY, BREAST_CANCER_PROG_CL_DELIM_WHITESPACE, BREAST_CANCER_PROG_CL_OUTPUT],
[BREAST_CANCER_PATH, BREAST_CANCER_HAS_HEADER, BREAST_CANCER_DATA_TYPES, BREAST_CANCER_IS_CLASSIFY, BREAST_CANCER_DELIM_WHITESPACE, BREAST_CANCER_OUTPUT],
[CAR_PATH, CAR_HAS_HEADER, CAR_DATA_TYPES, CAR_IS_CLASSIFY, CAR_DELIM_WHITESPACE, CAR_OUTPUT],
[CHESS_PATH, CHESS_HAS_HEADER, CHESS_DATA_TYPES, CHESS_IS_CLASSIFY, CHESS_DELIM_WHITESPACE, CHESS_OUTPUT],
[CLEVELAND_PATH, CLEVELAND_HAS_HEADER, CLEVELAND_DATA_TYPES, CLEVELAND_IS_CLASSIFY, CLEVELAND_DELIM_WHITESPACE, CLEVELAND_OUTPUT],
[CLIMATE_PATH, CLIMATE_HAS_HEADER, CLIMATE_DATA_TYPES, CLIMATE_IS_CLASSIFY, CLIMATE_DELIM_WHITESPACE, CLIMATE_OUTPUT],
[CMC_PATH, CMC_HAS_HEADER, CMC_DATA_TYPES, CMC_IS_CLASSIFY, CMC_DELIM_WHITESPACE, CMC_OUTPUT],
[CONNECTIONIST_PATH, CONNECTIONIST_HAS_HEADER, CONNECTIONIST_DATA_TYPES, CONNECTIONIST_IS_CLASSIFY, CONNECTIONIST_DELIM_WHITESPACE, CONNECTIONIST_OUTPUT],
[CREDIT_PATH, CREDIT_HAS_HEADER, CREDIT_DATA_TYPES, CREDIT_IS_CLASSIFY, CREDIT_DELIM_WHITESPACE, CREDIT_OUTPUT],
[CYLINDER_PATH, CYLINDER_HAS_HEADER, CYLINDER_DATA_TYPES, CYLINDER_IS_CLASSIFY, CYLINDER_DELIM_WHITESPACE, CYLINDER_OUTPUT],
[DIABETES_PATH, DIABETES_HAS_HEADER, DIABETES_DATA_TYPES, DIABETES_IS_CLASSIFY, DIABETES_DELIM_WHITESPACE, DIABETES_OUTPUT],
[DERMATOLOGY_PATH, DERMATOLOGY_HAS_HEADER, DERMATOLOGY_DATA_TYPES, DERMATOLOGY_IS_CLASSIFY, DERMATOLOGY_DELIM_WHITESPACE, DERMATOLOGY_OUTPUT],
[ECHOCARDIOGRAM_PATH, ECHOCARDIOGRAM_HAS_HEADER, ECHOCARDIOGRAM_DATA_TYPES, ECHOCARDIOGRAM_IS_CLASSIFY, ECHOCARDIOGRAM_DELIM_WHITESPACE, ECHOCARDIOGRAM_OUTPUT],
[FERTILITY_PATH, FERTILITY_HAS_HEADER, FERTILITY_DATA_TYPES, FERTILITY_IS_CLASSIFY, FERTILITY_DELIM_WHITESPACE, FERTILITY_OUTPUT],
[GERMAN_PATH, GERMAN_HAS_HEADER, GERMAN_DATA_TYPES, GERMAN_IS_CLASSIFY, GERMAN_DELIM_WHITESPACE, GERMAN_OUTPUT],
[HABERMAN_PATH, HABERMAN_HAS_HEADER, HABERMAN_DATA_TYPES, HABERMAN_IS_CLASSIFY, HABERMAN_DELIM_WHITESPACE, HABERMAN_OUTPUT],
[HAYES_PATH, HAYES_HAS_HEADER, HAYES_DATA_TYPES, HAYES_IS_CLASSIFY, HAYES_DELIM_WHITESPACE, HAYES_OUTPUT],
[HEPATITIS_PATH, HEPATITIS_HAS_HEADER, HEPATITIS_DATA_TYPES, HEPATITIS_IS_CLASSIFY, HEPATITIS_DELIM_WHITESPACE, HEPATITIS_OUTPUT],
[HOUSE_VOTES_PATH, HOUSE_VOTES_HAS_HEADER, HOUSE_VOTES_DATA_TYPES, HOUSE_VOTES_IS_CLASSIFY, HOUSE_VOTES_DELIM_WHITESPACE, HOUSE_VOTES_OUTPUT],
[ILP_PATH, ILP_HAS_HEADER, ILP_DATA_TYPES, ILP_IS_CLASSIFY, ILP_DELIM_WHITESPACE, ILP_OUTPUT],
[IMAGE_PATH, IMAGE_HAS_HEADER, IMAGE_DATA_TYPES, IMAGE_IS_CLASSIFY, IMAGE_DELIM_WHITESPACE, IMAGE_OUTPUT],
[IONOSPHERE_PATH, IONOSPHERE_HAS_HEADER, IONOSPHERE_DATA_TYPES, IONOSPHERE_IS_CLASSIFY, IONOSPHERE_DELIM_WHITESPACE, IONOSPHERE_OUTPUT],
[IRIS_PATH, IRIS_HAS_HEADER, IRIS_DATA_TYPES, IRIS_IS_CLASSIFY, IRIS_DELIM_WHITESPACE, IRIS_OUTPUT],
[LANDSAT_PATH, LANDSAT_HAS_HEADER, LANDSAT_DATA_TYPES, LANDSAT_IS_CLASSIFY, LANDSAT_DELIM_WHITESPACE, LANDSAT_OUTPUT],
[MAMMOGRAPHIC_PATH, MAMMOGRAPHIC_HAS_HEADER, MAMMOGRAPHIC_DATA_TYPES, MAMMOGRAPHIC_IS_CLASSIFY, MAMMOGRAPHIC_DELIM_WHITESPACE, MAMMOGRAPHIC_OUTPUT],
[MONKS_1_PATH, MONKS_HAS_HEADER, MONKS_DATA_TYPES, MONKS_IS_CLASSIFY, MONKS_DELIM_WHITESPACE, MONKS_1_OUTPUT],
[MONKS_2_PATH, MONKS_HAS_HEADER, MONKS_DATA_TYPES, MONKS_IS_CLASSIFY, MONKS_DELIM_WHITESPACE, MONKS_2_OUTPUT],
[MONKS_3_PATH, MONKS_HAS_HEADER, MONKS_DATA_TYPES, MONKS_IS_CLASSIFY, MONKS_DELIM_WHITESPACE, MONKS_3_OUTPUT],
[NEW_THYROID_PATH, NEW_THYROID_HAS_HEADER, NEW_THYROID_DATA_TYPES, NEW_THYROID_IS_CLASSIFY, NEW_THYROID_DELIM_WHITESPACE, NEW_THYROID_OUTPUT],
[OPTICAL_PATH, OPTICAL_HAS_HEADER, OPTICAL_DATA_TYPES, OPTICAL_IS_CLASSIFY, OPTICAL_DELIM_WHITESPACE, OPTICAL_OUTPUT],
[OZONE_8_PATH, OZONE_8_HAS_HEADER, OZONE_8_DATA_TYPES, OZONE_8_IS_CLASSIFY, OZONE_8_DELIM_WHITESPACE, OZONE_8_OUTPUT],
[OZONE_1_PATH, OZONE_1_HAS_HEADER, OZONE_1_DATA_TYPES, OZONE_1_IS_CLASSIFY, OZONE_1_DELIM_WHITESPACE, OZONE_1_OUTPUT],
[PARKINSONS_PATH, PARKINSONS_HAS_HEADER, PARKINSONS_DATA_TYPES, PARKINSONS_IS_CLASSIFY, PARKINSONS_DELIM_WHITESPACE, PARKINSONS_OUTPUT],
[PLRX_PATH, PLRX_HAS_HEADER, PLRX_DATA_TYPES, PLRX_IS_CLASSIFY, PLRX_DELIM_WHITESPACE, PLRX_OUTPUT],
[QSAR_PATH, QSAR_HAS_HEADER, QSAR_DATA_TYPES, QSAR_IS_CLASSIFY, QSAR_DELIM_WHITESPACE, QSAR_OUTPUT],
[SEEDS_PATH, SEEDS_HAS_HEADER, SEEDS_DATA_TYPES, SEEDS_IS_CLASSIFY, SEEDS_DELIM_WHITESPACE, SEEDS_OUTPUT],
[SEISMIC_PATH, SEISMIC_HAS_HEADER, SEISMIC_DATA_TYPES, SEISMIC_IS_CLASSIFY, SEISMIC_DELIM_WHITESPACE, SEISMIC_OUTPUT],
[SONAR_PATH, SONAR_HAS_HEADER, SONAR_DATA_TYPES, SONAR_IS_CLASSIFY, SONAR_DELIM_WHITESPACE, SONAR_OUTPUT],
[SOYBEAN_PATH, SOYBEAN_HAS_HEADER, SOYBEAN_DATA_TYPES, SOYBEAN_IS_CLASSIFY, SOYBEAN_DELIM_WHITESPACE, SOYBEAN_OUTPUT],
[SPAMBASE_PATH, SPAMBASE_HAS_HEADER, SPAMBASE_DATA_TYPES, SPAMBASE_IS_CLASSIFY, SPAMBASE_DELIM_WHITESPACE, SPAMBASE_OUTPUT],
[SPECT_PATH, SPECT_HAS_HEADER, SPECT_DATA_TYPES, SPECT_IS_CLASSIFY, SPECT_DELIM_WHITESPACE, SPECT_OUTPUT],
[SPECTF_PATH, SPECTF_HAS_HEADER, SPECTF_DATA_TYPES, SPECTF_IS_CLASSIFY, SPECTF_DELIM_WHITESPACE, SPECTF_OUTPUT],
[TAE_PATH, TAE_HAS_HEADER, TAE_DATA_TYPES, TAE_IS_CLASSIFY, TAE_DELIM_WHITESPACE, TAE_OUTPUT],
[THORAIC_PATH, THORAIC_HAS_HEADER, THORAIC_DATA_TYPES, THORAIC_IS_CLASSIFY, THORAIC_DELIM_WHITESPACE, THORAIC_OUTPUT],
[THYROID_ANN_PATH, THYROID_ANN_HAS_HEADER, THYROID_ANN_DATA_TYPES, THYROID_ANN_IS_CLASSIFY, THYROID_ANN_DELIM_WHITESPACE, THYROID_ANN_OUTPUT],
[TICTAC_PATH, TICTAC_HAS_HEADER, TICTAC_DATA_TYPES, TICTAC_IS_CLASSIFY, TICTAC_DELIM_WHITESPACE, TICTAC_OUTPUT],
[TRANSFUSION_PATH, TRANSFUSION_HAS_HEADER, TRANSFUSION_DATA_TYPES, TRANSFUSION_IS_CLASSIFY, TRANSFUSION_DELIM_WHITESPACE, TRANSFUSION_OUTPUT],
[WALL_PATH, WALL_HAS_HEADER, WALL_DATA_TYPES, WALL_IS_CLASSIFY, WALL_DELIM_WHITESPACE, WALL_OUTPUT],
[WINE_PATH, WINE_HAS_HEADER, WINE_DATA_TYPES, WINE_IS_CLASSIFY, WINE_DELIM_WHITESPACE, WINE_OUTPUT]]

def main():
    for arg in args:
        try:
            runCsv(arg[0], arg[1], arg[2], arg[3], arg[4], arg[5])
        except Exception:
            pass


if __name__ == "__main__":
    main()
